---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: pipeline-test
spec:
  apiServer:
    applyTektonCustomResource: true
    archiveLogs: false
    artifactSignedURLExpirySeconds: 60
    autoUpdatePipelineDefaultVersion: true
    caBundleFileMountPath: ""
    caBundleFileName: ""
    collectMetrics: true
    dbConfigConMaxLifetimeSec: 120
    deploy: true
    enableOauth: true
    enableSamplePipeline: true
    injectDefaultScript: true
    stripEOF: true
    terminateStatus: Cancelled
    trackArtifacts: true
  database:
    customExtraParams: '{"tls":"false"}'
    disableHealthChecks: false
    externalDB:
      host: mysql.database
      passwordSecret:
        key: dbpassword
        name: dbpassword
      pipelineDBName: pipelines
      port: "3306"
      username: user
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ""
      bucket: pipeline-artifacts
      host: minio.minio:9000
      port: ""
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
